Now compile on Windows
zodinyac/dupload pull request #6
Opened 2018-11-22 00:56 UTC by BDanAnd

2019-01-18 20:20 UTC, zodinyac requested changes

2019-01-18 20:20 UTC, zodinyac commented on CMakeLists.txt
> +    target_link_libraries( ${FILTER_NAME} Qt5::Core Qt5::Gui )
Уверен, что только эти либы?

2019-01-18 20:20 UTC, zodinyac commented on CMakeLists.txt
> +endforeach()
Добавь после пустую строку.

2019-01-18 20:20 UTC, zodinyac commented on src/dfilter.cpp
> +			continue;
Скобки { continue; }

2019-01-23 02:24 UTC, BDanAnd commented on CMakeLists.txt
> +    target_link_libraries( ${FILTER_NAME} Qt5::Core Qt5::Gui )
Ну вроде работает, если только они указаны.

2019-01-25 14:12 UTC, zodinyac approved these changes

2019-01-25 14:13 UTC, merged